name: Publish

on:
  workflow_run:
    workflows: Tests
    branches: main
    types: completed
  workflow_dispatch:
    inputs:
      release_pypi:
        description: 'Create a new PyPI release'
        type: boolean
        required: true
        default: true
      release_github:
        description: 'Create a new GitHub release'
        type: boolean
        required: true
        default: true        
     
jobs:
  build-and-release:
    if: contains(github.event.workflow_run.head_commit.message, 'Version') || github.event.inputs.release_pypi || github.event.inputs.release_github
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel build twine 
    - name: Build package (PyPI)
      if: contains(github.event.workflow_run.head_commit.message, 'Version') || github.event.inputs.release_pypi
      run: python -m build --no-isolation
    - name: Publish package (PyPI)
      if: contains(github.event.workflow_run.head_commit.message, 'Version') || github.event.inputs.release_pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload ./dist/*.whl --skip-existing
        twine upload ./dist/*.tar.gz --skip-existing